name: Build Workflow

on:
#  push:
#    branches: master
  workflow_dispatch:


jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Run Poetry
        uses: abatilo/actions-poetry@v2
        with: 
          poetry-version: "1.3.1"
      - name: Run PyInstaller
        run: |
          poetry install
          cd pyroll/gui
          poetry shell
          pyinstaller main.py --add-data="../../img/*;img/" --onefile --windowed --icon="../../img/pyroll_icon.png" --name="PyRoll"

      - name: create release
        id: create_release
        uses: softprops/action-gh-release@v1
        
        with:
          files: |
            pyroll/gui/dist/PyRoll.exe